#!/bin/bash

# Set decoration geometry
berryc border_width 0
berryc inner_border_width 2
berryc title_height 20
berryc top_gap 30

# Set decoration colors
berryc focus_color 292D3E
berryc unfocus_color 292D3E
berryc inner_focus_color 58a6ff
berryc inner_unfocus_color 0d1117
berryc text_focus_color ffffff
berryc text_unfocus_color b1bac4

# Other options
berryc smart_place "true"
berryc draw_text "true"
berryc edge_lock "true"
berryc set_font "BlexMono Nerd Font"
berryc name_desktop 0 A
berryc name_desktop 1 B
berryc name_desktop 2 C
berryc name_desktop 3 D
berryc name_desktop 4 E
berryc name_desktop 5 F
berryc name_desktop 6 G
berryc name_desktop 7 H
berryc name_desktop 8 I
berryc name_desktop 9 J

sxhkd -c ~/.config/berry/sxhkdrc &
picom &
tint2 &
nitrogen --restore
