#!/bin/bash

# Set decoration geometry
berryc border_width 0
berryc inner_border_width 2
berryc title_height 20
berryc top_gap 30

# Set decoration colors
berryc focus_color 292D3E
berryc unfocus_color 292D3E
berryc inner_focus_color 58a6ff
berryc inner_unfocus_color 0d1117
berryc text_focus_color ffffff
berryc text_unfocus_color b1bac4

# Other options
berryc smart_place "true"
berryc draw_text "true"
berryc edge_lock "true"
berryc set_font "BlexMono Nerd Font"

sxhkd -c ~/.config/berry/sxhkdrc &
picom &
tint2 &
feh --bg-scale ~/.gitshit/wallpapers/0005.jpg
