#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d A B C D E F G H I J

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config normal_border_color "#0d1117"
bspc config focused_border_color "#58a6ff"
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

tint2 &
picom &
sxhkd -c ~/.config/bspwm/sxhkdrc &
feh --bg-scale ~/.gitshit/wallpapers/0005.jpg
